from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from .views import (
    AvailabilityListCreateAPIView,
    AvailabilityRetrieveUpdateDestroyAPIView,
    CurriculumListCreateAPIView,
    CurriculumRetrieveUpdateDestroyAPIView,
    DomainRetrieveUpdateDestroyAPIView,
    # HomePageView,
    MenteeRetrieveUpdateDestroyAPIView,
    MentorListCreateAPIView, 
    MenteeListCreateAPIView,
    MentorRetrieveUpdateDestroyAPIView,
    NotificationListCreateAPIView,
    NotificationRetrieveUpdateDestroyAPIView,
    ProjectListCreateAPIView,
    ProjectRetrieveUpdateDestroyAPIView,
    ReviewListCreateAPIView,
    ReviewRetrieveUpdateDestroyAPIView,
    SessionListCreateAPIView,
    SessionRetrieveUpdateDestroyAPIView,
    SkillCoveredListCreateAPIView,
    SkillCoveredRetrieveUpdateDestroyAPIView,
    SkillListCreateAPIView,
    DomainListCreateAPIView,
    SkillRetrieveUpdateDestroyAPIView,
    UserListCreateAPIView,
    UserRetrieveUpdateDestroyAPIView,
)

urlpatterns = [
    # path('', HomePageView.as_view(), name='home'),
    path('api/user/', UserListCreateAPIView.as_view(), name='register'),
    path('api/user/<int:pk>/', UserRetrieveUpdateDestroyAPIView.as_view(), name='register'),
    path('api/mentors/', MentorListCreateAPIView.as_view(), name='mentors-list-create'),
    path('api/mentors/<int:pk>/', MentorRetrieveUpdateDestroyAPIView.as_view(), name='mentors-detail'),
    path('api/mentees/', MenteeListCreateAPIView.as_view(), name='mentees-list-create'),
    path('api/mentees/<int:pk>/', MenteeRetrieveUpdateDestroyAPIView.as_view(), name='mentees-detail'),
    path('api/skills/', SkillListCreateAPIView.as_view(), name='skills-list-create'),
    path('api/skills/<int:pk>/', SkillRetrieveUpdateDestroyAPIView.as_view(), name='skills-detail'),
    path('api/domains/', DomainListCreateAPIView.as_view(), name='domains-list-create'),
    path('api/domains/<int:pk>/', DomainRetrieveUpdateDestroyAPIView.as_view(), name='domains-detail'),
    path('api/reviews/', ReviewListCreateAPIView.as_view(), name='review-list-create'),
    path('api/reviews/<int:pk>/', ReviewRetrieveUpdateDestroyAPIView.as_view(), name='review-retrieve-update-destroy'),
    path('api/skills-covered/', SkillCoveredListCreateAPIView.as_view(), name='skill_covered_list_create'),
    path('api/skills-covered/<int:pk>/', SkillCoveredRetrieveUpdateDestroyAPIView.as_view(), name='skill_covered_retrieve_update_destroy'),
     path('api/curriculum/', CurriculumListCreateAPIView.as_view(), name='curriculum_list_create'),
    path('api/curriculum/<int:pk>/', CurriculumRetrieveUpdateDestroyAPIView.as_view(), name='curriculum_retrieve_update_destroy'),
    path('api/project/', ProjectListCreateAPIView.as_view(), name='project_list_create'),
    path('api/project/<int:pk>/', ProjectRetrieveUpdateDestroyAPIView.as_view(), name='project_retrieve_update_destroy'),
    path('api/session/', SessionListCreateAPIView.as_view(), name='session_list_create'),
    path('api/session/<int:pk>/', SessionRetrieveUpdateDestroyAPIView.as_view(), name='session_retrieve_update_destroy'),
    path('api/availability/', AvailabilityListCreateAPIView.as_view(), name='availability_list_create'),
    path('api/availability/<int:pk>/', AvailabilityRetrieveUpdateDestroyAPIView.as_view(), name='availability_retrieve_update_destroy'),
    path('notifications/', NotificationListCreateAPIView.as_view(), name='notification_list'),
    path('notifications/mark-read/', NotificationRetrieveUpdateDestroyAPIView.as_view(), name='notification_mark_read'),
]
